version: "3.8"
services:
  db:
    image: mysql:8.0
    environment:
      - MYSQL_USER=mdWiki
      - MYSQL_PASSWORD=mdWiki
      - MYSQL_ROOT_PASSWORD=mdWiki
    ports:
      - 3306:3306
    restart: unless-stopped

  api:
    ports:
      - 8000:8000
    build:
      context: ./services
      dockerfile: ./Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - SECRET=mysecretvariable
      - DB_USER=mdWiki
      - DB_PASSWORD=mdWiki