FROM node:18-alpine
WORKDIR /usr/src/app
COPY package.json package-lock.json ./
COPY backend/package.json backend/tsconfig.json backend/
COPY backend/migrations backend/migrations
COPY backend/scripts backend/scripts
COPY backend/src backend/src
RUN npm ci
RUN npm run build
EXPOSE 8000
CMD npm start