name: Build and upload to S3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_BUCKET: md-wiki.frontend.builds

    steps:
      - uses: actions/checkout@v2
        name: Checkout

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          npm ci

      - name: Build
        run: |
          npm run build -w frontend

      - id: commit
        uses: pr-mpt/actions-commit-hash@v2
        name: Get commit hash

      - name: Create artifacts directory
        run: mkdir artifacts

      - name: Install zip
        uses: montudor/action-zip@v1

      - name: Zip build bundle
        run: zip -qq -r ../../artifacts/build.${{ steps.commit.outputs.short }}.zip *
        working-directory: frontend/build

      - uses: shallwefootball/s3-upload-action@master
        name: Upload bundle to S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ env.AWS_BUCKET }}
          source_dir: artifacts
